name: virtual_salao
description: Aplicativo de salão de barbearia com geolocalização.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  geolocator: ^10.1.1
  http: ^1.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  image_picker: ^1.0.7
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/logo_vs.png
    - assets/images/apple_icon.png
    - assets/images/google_icon.png
    - assets/images/

