// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fXY3VZrRHbiORSNOLa8g8trNUO5jBks',
    appId: '1:653696170009:web:0b650370bb29e29c52d288',
    messagingSenderId: '653696170009',
    projectId: 'virtual-salao-f8532',
    authDomain: 'virtual-salao-f8532.firebaseapp.com',
    storageBucket: 'virtual-salao-f8532.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fXY3VZrRHbiORSNOLa8g8trNUO5jBks',
    appId: '1:653696170009:android:7b9894badcf1a5ba52d288',
    messagingSenderId: '653696170009',
    projectId: 'virtual-salao-f8532',
    storageBucket: 'virtual-salao-f8532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fXY3VZrRHbiORSNOLa8g8trNUO5jBks',
    appId: '1:653696170009:ios:7b9894badcf1a5ba52d288',
    messagingSenderId: '653696170009',
    projectId: 'virtual-salao-f8532',
    storageBucket: 'virtual-salao-f8532.firebasestorage.app',
    iosBundleId: 'com.example.virtualSalao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fXY3VZrRHbiORSNOLa8g8trNUO5jBks',
    appId: '1:653696170009:macos:7b9894badcf1a5ba52d288',
    messagingSenderId: '653696170009',
    projectId: 'virtual-salao-f8532',
    storageBucket: 'virtual-salao-f8532.firebasestorage.app',
    iosBundleId: 'com.example.virtualSalao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_fXY3VZrRHbiORSNOLa8g8trNUO5jBks',
    appId: '1:653696170009:windows:7b9894badcf1a5ba52d288',
    messagingSenderId: '653696170009',
    projectId: 'virtual-salao-f8532',
    storageBucket: 'virtual-salao-f8532.firebasestorage.app',
  );
}
